### ISSUE TITLE
[ UI ] If the logo name and the dark mode icon be on the same line it would look perfect in mobile as well as in Desktop View

### ISSUE THREAD

**Issue by AnirudhPanda** [anushbhatia/devtree#12]

**Comment by AnirudhPanda** [comment]
Hey @anushbhatia should I track the package.lock.json file from my local too or keep it in gitignore. After npm install, it added a package.lock.json file which I didn't find in your repository.

**Comment by AnirudhPanda** [comment]
I am creating the PR, suggest changes.

**Comment by anushbhatia** [comment]
add yarn-lock in gitignore not package-lock.json
refer to this
https://stackoverflow.com/questions/48524417/should-the-package-lock-json-file-be-added-to-gitignore

**Comment by AnirudhPanda** [comment]
> add yarn-lock in gitignore not package-lock.json
> refer to this
> https://stackoverflow.com/questions/48524417/should-the-package-lock-json-file-be-added-to-gitignore

added yarn.lock in gitignore
