### ISSUE TITLE
Add various Social Media Profiles from internet

### ISSUE THREAD

**Issue by shvam0000** [anushbhatia/devtree#2]
We can add the following social media handles - 
1. Medium
2. Stackoverflow
3. Dev.to
4. Buy me coffee
5. Facebook
6. Hackerrank / HackerEarth / Codechef etc. coding platform pages

I would like to work on these additions, so it'd be great if you assign this issue to me.

**Comment by anushbhatia** [comment]
Do find the relevant animations if that's not there do let me know. I can help you design it on XD/Figma.

**Comment by shvam0000** [comment]
Can you please provide the images for the social media handles?
