### ISSUE TITLE
Design a favicon for the website

### ISSUE THREAD

**Issue by anushbhatia** [anushbhatia/devtree#4]
Currently, we just have a react logo there so we have to replace that with a custom profile picture or A common developer's favicon.

**Comment by varunwho** [comment]
Hey can you assign this to me? And also can you tell what are your expectations of the design if possible (briefly an overall idea)
(What I was thinking was to have a common developer's favicon)

**Comment by anushbhatia** [comment]
https://www.flaticon.com/free-icon/coding_1290020 something like this
Anything which looks more like a developer icon
