### ISSUE TITLE
Light mode for the website (along with a toggle switch)

### ISSUE THREAD

**Issue by varunwho** [anushbhatia/devtree#6]

**Comment by anushbhatia** [comment]
Anu updates?

**Comment by varunwho** [comment]
> Anu updates?

Yea it's almost done, only the text inside the card's colour has to be toggled.

**Comment by varunwho** [comment]
I'm not able to change the color of the text inside the card while toggling, rest everything else is done

**Comment by anushbhatia** [comment]
Give the pr i will look into that and suggest the solution if possible.

**Comment by varunwho** [comment]
> Give the pr i will look into that and suggest the solution if possible.

Give me a day's time, I'll try if I can do it myself

**Comment by varunwho** [comment]
@anushbhatia I was able to do it and I've generated a PR 🙌🏻
